# This docker-compose is only used when developing locally
# As this website deploys to vercel, there is no docker-compose for production.
version: "3.4"

services:
  # Create the posgres database
  database:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project3-it2810
    volumes:
      - database-datab:/var/lib/postgresql/data/ # persist data even if container shuts down

  # Start the frontend web server
  frontend:
    depends_on:
      - database
    build:
      context: ./
      dockerfile: ./Dockerfile.frontend.prod
    restart: always
    image: project3-frontend
    environment:
      NODE_ENV: production
    ports:
      - "3500:80"

  # Start the backend web server
  backend:
    depends_on:
      - database
    restart: always
    image: project3-backend
    build:
      context: ./
      dockerfile: ./Dockerfile.backend
    environment:
      NODE_ENV: development
    ports:
      - "4000:4000"
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "npm run prepareuse && cd project3-backend && npm run build && npm run start:prod",
      ]
# Keep database data across instances
volumes:
  database-datab:
